# Generated by Django 5.1.4 on 2025-01-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='last_attempt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='phoneotp',
            table=None,
        ),
    ]
