# Generated by Django 5.1.4 on 2025-02-05 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_commission_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_slider', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(blank=True, choices=[('SIDEBAR', 'Sidebar'), ('FULL_WIDTH', 'Full Width'), ('PRODUCT_PAGE', 'Product Page'), ('CUSTOMER_PANEL', 'Customer Panel'), ('MLM_PANEL', 'MLM Panel')], default='SIDEBAR', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='metatag',
            name='blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.blog'),
        ),
    ]
