# Generated by Django 5.1.4 on 2025-03-07 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_shippingconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickupaddress',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Pickup Address', 'verbose_name_plural': 'Pickup Addresses'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shipment', 'verbose_name_plural': 'Shipments'},
        ),
        migrations.AlterModelOptions(
            name='shipmentstatusupdate',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Shipment Status Update', 'verbose_name_plural': 'Shipment Status Updates'},
        ),
        migrations.AlterModelOptions(
            name='shippingconfig',
            options={'verbose_name': 'Shipping Configuration', 'verbose_name_plural': 'Shipping Configurations'},
        ),
        migrations.RemoveField(
            model_name='shippingconfig',
            name='enable_shipping',
        ),
        migrations.AddField(
            model_name='order',
            name='orderType',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('COD', 'Cod')], default='ONLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='quixgo_firstName',
            field=models.CharField(blank=True, help_text='First name registered with QuixGo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='quixgo_lastName',
            field=models.CharField(blank=True, help_text='Last name registered with QuixGo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='quixgo_mobile',
            field=models.CharField(blank=True, help_text='Mobile number registered with QuixGo', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='address_id',
            field=models.CharField(blank=True, help_text='QuixGo address ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='address_line1',
            field=models.CharField(help_text='Address line 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Address line 2 (optional)', max_length=255),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='address_type',
            field=models.CharField(default='Office', help_text='Address type (Home, Office, Warehouse)', max_length=20),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Alternate phone (optional)', max_length=15),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='city',
            field=models.CharField(help_text='City', max_length=100),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='contact_person',
            field=models.CharField(help_text='Contact person name', max_length=100),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='country',
            field=models.CharField(default='India', help_text='Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='customer_id',
            field=models.CharField(blank=True, help_text='QuixGo customer ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='email',
            field=models.EmailField(blank=True, help_text='Email (optional)', max_length=254),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Address is active and available for use'),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use as default pickup address'),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='landmark',
            field=models.CharField(blank=True, help_text='Landmark (optional)', max_length=255),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='name',
            field=models.CharField(help_text='Name for this pickup point', max_length=100),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='phone',
            field=models.CharField(help_text='Contact phone', max_length=15),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='pincode',
            field=models.CharField(help_text='PIN code', max_length=10),
        ),
        migrations.AlterField(
            model_name='pickupaddress',
            name='state',
            field=models.CharField(help_text='State', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='awb_number',
            field=models.CharField(blank=True, help_text='AWB tracking number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cod_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='COD amount to be collected', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='courier_name',
            field=models.CharField(blank=True, help_text='Courier service provider (DLV, DTC, SFX)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='height',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Height in cm', max_digits=5),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Whether this shipment has been cancelled'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='is_cod',
            field=models.BooleanField(default=False, help_text='Whether this is a Cash on Delivery shipment'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='length',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Length in cm', max_digits=5),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(help_text='Order being shipped', on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='home.order'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pickup_address',
            field=models.ForeignKey(help_text='Pickup address for this shipment', on_delete=django.db.models.deletion.PROTECT, to='home.pickupaddress'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='service_type',
            field=models.CharField(default='SF', help_text='Service type (Express=EXP or Surface=SF)', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_id',
            field=models.CharField(blank=True, help_text='QuixGo shipment ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping charge for this shipment', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED_DELIVERY', 'Failed Delivery'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the shipment', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status_details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional status details as JSON'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='URL for tracking this shipment', null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weight in kg', max_digits=5),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='width',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Width in cm', max_digits=5),
        ),
        migrations.AlterField(
            model_name='shipmentstatusupdate',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the status update', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipmentstatusupdate',
            name='shipment',
            field=models.ForeignKey(help_text='Related shipment', on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='home.shipment'),
        ),
        migrations.AlterField(
            model_name='shipmentstatusupdate',
            name='status',
            field=models.CharField(help_text='Status name', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipmentstatusupdate',
            name='status_details',
            field=models.TextField(blank=True, help_text='Status details or comments'),
        ),
        migrations.AlterField(
            model_name='shipmentstatusupdate',
            name='timestamp',
            field=models.DateTimeField(help_text='When this status was updated'),
        ),
        migrations.AlterField(
            model_name='shippingconfig',
            name='auth_token',
            field=models.TextField(blank=True, help_text='JWT token for API authentication', null=True),
        ),
        migrations.AlterField(
            model_name='shippingconfig',
            name='default_courier',
            field=models.CharField(default='DTC', help_text='Default courier service provider (DTC, DLV, SFX, etc.)', max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingconfig',
            name='default_service_type',
            field=models.CharField(default='SF', help_text='Default service type (SF=Surface, EXP=Express)', max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingconfig',
            name='quixgo_api_base_url',
            field=models.URLField(default='https://api.quixgo.com/clientApi', help_text='QuixGo API base URL (production/development)'),
        ),
        migrations.AlterField(
            model_name='shippingconfig',
            name='quixgo_customer_id',
            field=models.CharField(blank=True, help_text='Customer ID received from QuixGo API (annotation_id)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingconfig',
            name='quixgo_email',
            field=models.EmailField(help_text='Email for QuixGo account login', max_length=254),
        ),
        migrations.AlterField(
            model_name='shippingconfig',
            name='quixgo_password',
            field=models.CharField(help_text='Password for QuixGo account', max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingconfig',
            name='token_expiry',
            field=models.DateTimeField(blank=True, help_text='Token expiry date/time', null=True),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order', 'status'], name='home_shipme_order_i_bf2702_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['awb_number'], name='home_shipme_awb_num_3c4d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentstatusupdate',
            index=models.Index(fields=['shipment', 'timestamp'], name='home_shipme_shipmen_6ce17e_idx'),
        ),
    ]
