# Generated by Django 5.1.4 on 2025-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_pickupaddress_options_alter_shipment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingCredential',
        ),
        migrations.AlterModelOptions(
            name='shippingconfig',
            options={},
        ),
        migrations.RemoveField(
            model_name='shippingconfig',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='shippingconfig',
            name='quixgo_api_base_url',
        ),
        migrations.RemoveField(
            model_name='shippingconfig',
            name='quixgo_customer_id',
        ),
        migrations.RemoveField(
            model_name='shippingconfig',
            name='quixgo_email',
        ),
        migrations.RemoveField(
            model_name='shippingconfig',
            name='quixgo_firstName',
        ),
        migrations.RemoveField(
            model_name='shippingconfig',
            name='quixgo_lastName',
        ),
        migrations.RemoveField(
            model_name='shippingconfig',
            name='quixgo_mobile',
        ),
        migrations.RemoveField(
            model_name='shippingconfig',
            name='quixgo_password',
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingconfig',
            name='default_courier',
            field=models.CharField(default='DTC', max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingconfig',
            name='default_service_type',
            field=models.CharField(default='SF', max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingconfig',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
