# Generated by Django 5.1.4 on 2025-02-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_product_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(blank=True, choices=[('SIDEBAR', 'Sidebar'), ('FULL_WIDTH', 'Full Width'), ('PRODUCT_PAGE', 'Product Page'), ('CUSTOMER_PANEL', 'Customer Panel'), ('MLM_PANEL', 'MLM Panel')], default='SIDEBAR', max_length=100, null=True),
        ),
    ]
