# Generated by Django 5.1.4 on 2025-02-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passwordresetrequest',
            table='password_reset_requests',
        ),
    ]
