# Generated by Django 5.1.4 on 2025-02-23 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_passwordresetrequest_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reset_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
