# Generated by Django 5.1.4 on 2025-02-24 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_passwordresetrequest_processed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionActivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('current_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_requests', to='home.position')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_commission_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_activation_requests', to='home.mlmmember')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downline_commission_requests', to='home.mlmmember')),
                ('target_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_commission_requests', to='home.position')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('requester', 'sponsor')},
            },
        ),
    ]
