# Generated by Django 5.1.4 on 2025-02-24 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_commissionactivationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionactivationrequest',
            name='current_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_commission_requests', to='home.position'),
        ),
        migrations.AlterField(
            model_name='commissionactivationrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_commission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commissionactivationrequest',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downline_commission_requests', to='home.mlmmember'),
        ),
        migrations.AlterField(
            model_name='product',
            name='HSN_Code',
            field=models.SlugField(null=True),
        ),
    ]
