# Generated by Django 5.1.4 on 2025-02-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_pickupaddress_shippingcredential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='is_first_purchase_bonus',
            field=models.BooleanField(default=False, help_text='Flag to indicate if this is a first purchase bonus commission'),
        ),
        migrations.AddField(
            model_name='mlmmember',
            name='first_purchase_bonus_received',
            field=models.BooleanField(default=False, help_text='Flag to track if first purchase bonus has been received'),
        ),
    ]
