# Generated by Django 5.1.4 on 2025-02-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_commission_is_first_purchase_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='calculation_month',
            field=models.DateField(blank=True, help_text='For monthly calculations, the first day of the month this calculation represents', null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='commission_type',
            field=models.CharField(choices=[('ORDER', 'Order Commission'), ('MONTHLY', 'Monthly Calculation'), ('BONUS', 'First Purchase Bonus'), ('SPECIAL', 'Special Promotion')], default='MONTHLY', max_length=10),
        ),
        migrations.AddField(
            model_name='commission',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['member', 'date'], name='commissions_member__d583ce_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['from_member', 'date'], name='commissions_from_me_a4c8de_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['calculation_month'], name='commissions_calcula_b25426_idx'),
        ),
    ]
