# Generated by Django 5.1.4 on 2025-03-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_commission_calculation_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmmember',
            name='first_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of first payment made by member', max_digits=10),
        ),
        migrations.AddField(
            model_name='mlmmember',
            name='first_payment_complete',
            field=models.BooleanField(default=False, help_text='Flag to track if first payment requirement has been met'),
        ),
    ]
