# Generated by Django 5.1.4 on 2025-03-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_mlmmember_first_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmmember',
            name='last_commission_calculation',
            field=models.DateTimeField(blank=True, help_text='Date of last commission calculation', null=True),
        ),
        migrations.AddField(
            model_name='mlmmember',
            name='monthly_quota_maintained',
            field=models.BooleanField(default=False, help_text='Flag indicating if monthly quota is maintained for current month'),
        ),
    ]
